/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import training.center.Course;
import training.center.MyException;
/**
 *
 * @author User
 */
public class AddCourse extends javax.swing.JPanel {

    /**
     * Creates new form AddCourse
     */
    public AddCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCoursename = new javax.swing.JLabel();
        jLabelCourseid = new javax.swing.JLabel();
        jLabelHours = new javax.swing.JLabel();
        jButtonSubmitCourse = new javax.swing.JButton();
        jTextFieldCourseName = new javax.swing.JTextField();
        jTextFieldCourseID = new javax.swing.JTextField();
        jLabelCourseid1 = new javax.swing.JLabel();
        jTextFieldprice = new javax.swing.JTextField();
        jLabelHours1 = new javax.swing.JLabel();
        jTextFieldHours1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLecNum = new javax.swing.JTextField();
        Message = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCoursename.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabelCoursename.setForeground(new java.awt.Color(106, 135, 157));
        jLabelCoursename.setText("Course Name");
        add(jLabelCoursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabelCourseid.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabelCourseid.setForeground(new java.awt.Color(106, 135, 157));
        jLabelCourseid.setText("Course ID");
        add(jLabelCourseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabelHours.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabelHours.setForeground(new java.awt.Color(106, 135, 157));
        jLabelHours.setText("Credit Hours");
        add(jLabelHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jButtonSubmitCourse.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonSubmitCourse.setForeground(new java.awt.Color(106, 135, 157));
        jButtonSubmitCourse.setText("Submit");
        jButtonSubmitCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitCourseActionPerformed(evt);
            }
        });
        add(jButtonSubmitCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jTextFieldCourseName.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldCourseName.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCourseNameActionPerformed(evt);
            }
        });
        add(jTextFieldCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 200, -1));

        jTextFieldCourseID.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldCourseID.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCourseIDActionPerformed(evt);
            }
        });
        add(jTextFieldCourseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, -1));

        jLabelCourseid1.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabelCourseid1.setForeground(new java.awt.Color(106, 135, 157));
        jLabelCourseid1.setText("Lec Num");
        add(jLabelCourseid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jTextFieldprice.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldprice.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 200, -1));

        jLabelHours1.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabelHours1.setForeground(new java.awt.Color(106, 135, 157));
        jLabelHours1.setText("price");
        add(jLabelHours1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jTextFieldHours1.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldHours1.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldHours1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHours1ActionPerformed(evt);
            }
        });
        add(jTextFieldHours1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 200, -1));

        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jTextFieldLecNum.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldLecNum.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldLecNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 200, -1));
        add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 180, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beshoy sameh\\Desktop\\Project al 5ames\\GUI PHOTOS\\Admin\\add-delete course.jpg")); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 490));
    }// </editor-fold>//GEN-END:initComponents
MyException e=new MyException();
    private void jTextFieldCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCourseNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldCourseNameActionPerformed

    private void jButtonSubmitCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitCourseActionPerformed
        // TODO add your handling code here:
        jTextFieldCourseName.setText(e.checkFoundNameCours(jTextFieldCourseName.getText()));
        jTextFieldHours1.setText(e.CheckPositive(jTextFieldHours1.getText()));
        jTextFieldLecNum.setText(e.CheckPositive(jTextFieldLecNum.getText()));
        jTextFieldprice.setText(e.CheckPositive(jTextFieldprice.getText()));
        jTextFieldCourseID.setText(e.CheckPositive(jTextFieldCourseID.getText()));
        jTextFieldCourseID.setText(e.checkFoundIdCours(jTextFieldCourseID.getText()));
        if ( !jTextFieldCourseName.getText().equals("") || !jTextFieldCourseID.getText().equals("") ||  !jTextFieldHours1.getText().equals("") ||  !jTextFieldLecNum.getText().equals("") ||  !jTextFieldprice.getText().equals("") ){
            Course x = new Course();
            x.setName(jTextFieldCourseName.getText());
            x.setID(Integer.parseInt(jTextFieldCourseID.getText()));
            x.setHours(Integer.parseInt(jTextFieldHours1.getText()));
            x.setLecNum(Integer.parseInt(jTextFieldLecNum.getText()));
            x.setPrice(Double.parseDouble(jTextFieldprice.getText()));
            if (x.Add()) {
                Message.setText("Done");
                resetPanelData();
            } else {
               Message.setText("Failed");
            }
        }
        else
        {
            Message.setText("Please Fill All Fields");
        }
        
    }//GEN-LAST:event_jButtonSubmitCourseActionPerformed
protected void resetPanelData() {
        jTextFieldCourseName.setText("");
        jTextFieldCourseID.setText("");
        jTextFieldHours1.setText("");
        jTextFieldLecNum.setText("");
        jTextFieldprice.setText("");
        
    }
    private void jTextFieldHours1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHours1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHours1ActionPerformed

    private void jTextFieldCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCourseIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JButton jButtonSubmitCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCourseid;
    private javax.swing.JLabel jLabelCourseid1;
    private javax.swing.JLabel jLabelCoursename;
    private javax.swing.JLabel jLabelHours;
    private javax.swing.JLabel jLabelHours1;
    private javax.swing.JTextField jTextFieldCourseID;
    private javax.swing.JTextField jTextFieldCourseName;
    private javax.swing.JTextField jTextFieldHours1;
    private javax.swing.JTextField jTextFieldLecNum;
    private javax.swing.JTextField jTextFieldprice;
    // End of variables declaration//GEN-END:variables
}
