/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import training.center.Email;
import training.center.MyException;
/**
 *
 * @author Abanoub
 */
public class AddMail extends javax.swing.JPanel {

    /**
     * Creates new form Mail
     */
    public AddMail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jTextFieldSubject = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        Message = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 135, 157));
        jLabel2.setText("To");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jTextFieldMail.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        jTextFieldMail.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldMail.setOpaque(false);
        jTextFieldMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailActionPerformed(evt);
            }
        });
        add(jTextFieldMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, -1));

        jTextFieldSubject.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        jTextFieldSubject.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldSubject.setOpaque(false);
        add(jTextFieldSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 135, 157));
        jLabel3.setText("Subject");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jTextFieldCC.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        jTextFieldCC.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldCC.setOpaque(false);
        add(jTextFieldCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 210, -1));

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        jTextAreaMessage.setForeground(new java.awt.Color(106, 135, 157));
        jTextAreaMessage.setRows(5);
        jTextAreaMessage.setText("EK | Training Center\nHi ");
        jTextAreaMessage.setOpaque(false);
        jScrollPane1.setViewportView(jTextAreaMessage);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 210, 160));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(106, 135, 157));
        jLabel5.setText("Message");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 135, 157));
        jLabel6.setText("CC");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jButton1.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(106, 135, 157));
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jButtonReset.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(106, 135, 157));
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        Message.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beshoy sameh\\Desktop\\Project al 5ames\\GUI PHOTOS\\Admin\\SendMail.jpg")); // NOI18N
        Message.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
MyException e= new MyException();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextFieldMail.setText(e.checkEmail(jTextFieldMail.getText()));
        if (!jTextFieldMail.getText().equals("") && !jTextFieldSubject.getText().equals("")  &&!jTextAreaMessage.getText().equals("")) {
            try {
                Email e = new Email(jTextFieldMail.getText(), jTextFieldCC.getText(), jTextFieldSubject.getText(), jTextAreaMessage.getText());
                e.generateAndSendEmail();

                Message.setText("Your message has been sent.");

            } catch (MessagingException ex) {
                Message.setText("Your message hasn't been delivered.");
                Logger.getLogger(AddMail.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Message.setText("Missing required Fields ... !  Please, complete them before submit ...!");
        }
    
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMailActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldMail.setText("");
        jTextFieldCC.setText("");
        jTextFieldSubject.setText("");
        jTextAreaMessage.setText("");
        Message.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMessage;
    private javax.swing.JTextField jTextFieldCC;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldSubject;
    // End of variables declaration//GEN-END:variables
}
