/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import training.center.Student;
import training.center.MyException;
//import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AddStudent extends javax.swing.JPanel {

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPassWordField2 = new javax.swing.JPasswordField();
        ButtonSubmitStudent = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jIDField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFNField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jAgeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLNField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jEmailField = new javax.swing.JTextField();
        jfieldusername = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPassWordField1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPassWordField2.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jPassWordField2.setForeground(new java.awt.Color(106, 135, 157));
        add(jPassWordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 290, -1));

        ButtonSubmitStudent.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        ButtonSubmitStudent.setForeground(new java.awt.Color(106, 135, 157));
        ButtonSubmitStudent.setText("Submit");
        ButtonSubmitStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitStudentActionPerformed(evt);
            }
        });
        add(ButtonSubmitStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        ButtonReset.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        ButtonReset.setForeground(new java.awt.Color(106, 135, 157));
        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });
        add(ButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 135, 157));
        jLabel1.setText("ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jIDField.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jIDField.setForeground(new java.awt.Color(106, 135, 157));
        add(jIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 210, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 135, 157));
        jLabel6.setText("Repeat Pass");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 135, 157));
        jLabel2.setText("First name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jFNField.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jFNField.setForeground(new java.awt.Color(106, 135, 157));
        add(jFNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 125, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(106, 135, 157));
        jLabel7.setText("Age");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jAgeField.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jAgeField.setForeground(new java.awt.Color(106, 135, 157));
        add(jAgeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 290, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 135, 157));
        jLabel3.setText("Last name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLNField.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jLNField.setForeground(new java.awt.Color(106, 135, 157));
        add(jLNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 90, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 135, 157));
        jLabel4.setText("Email");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jEmailField.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jEmailField.setForeground(new java.awt.Color(106, 135, 157));
        add(jEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 290, -1));

        jfieldusername.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jfieldusername.setForeground(new java.awt.Color(106, 135, 157));
        add(jfieldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 290, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(106, 135, 157));
        jLabel11.setText("Username");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(106, 135, 157));
        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jPassWordField1.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jPassWordField1.setForeground(new java.awt.Color(106, 135, 157));
        add(jPassWordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 290, -1));

        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));
        add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 180, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beshoy sameh\\Desktop\\Project al 5ames\\GUI PHOTOS\\Student\\View grades.jpg")); // NOI18N
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));
    }// </editor-fold>//GEN-END:initComponents
MyException e=new MyException();
    private void ButtonSubmitStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubmitStudentActionPerformed
        // TODO add your handling code here:
        jIDField.setText(e.CheckPositive(jIDField.getText()));
        jEmailField.setText(e.checkEmail(jEmailField.getText()));
        jPassWordField1.setText(e.checkPassLength(jPassWordField1.getText()));
        jfieldusername.setText(e.checkFoundUserName(jfieldusername.getText()));
        jIDField.setText(e.checkFoundIdStudent(jIDField.getText()));
        jAgeField.setText(e.CheckPositive(jAgeField.getText()));
        if (!jIDField.getText().equals("") && !jFNField.getText().equals("") && !jLNField.getText().equals("") && !jfieldusername.getText().equals("") && !jEmailField.getText().equals("") && !jPassWordField1.getText().equals("") && !jPassWordField2.getText().equals("") && !jAgeField.getText().equals(""))
        {

            Student s = new Student();
            s.setID(Integer.parseInt(jIDField.getText()));
            s.setFName(jFNField.getText());
            s.setLName(jLNField.getText());
            s.setEmail(jEmailField.getText());
            if (jPassWordField1.getText().equals(jPassWordField2.getText())) {
                s.setPass(jPassWordField1.getText());
            }
            s.setUserName(jfieldusername.getText());
            s.setAge(Integer.parseInt(jAgeField.getText()));
            
            //// al add b2a
            if (s.Add())
            {
                Message.setText("Done");
                resetPanelData();
            }
            else{
                
            Message.setText("Failed");
            }
            
            
        
           // JOptionPane.showMessageDialog(ButtonSubmitStudent, evt);
        
    }//GEN-LAST:event_ButtonSubmitStudentActionPerformed
    else{
                Message.setText("please Fill all Fields");
         }
        
       // else{JOptionPane.showMessageDialog(ButtonSubmitStudent, evt);}
        
        }
    
    protected void resetPanelData() {
        jIDField.setText("");
        jFNField.setText("");
        jLNField.setText("");
        jfieldusername.setText("");
        jPassWordField1.setText("");
        jPassWordField2.setText("");
        jAgeField.setText("");
        jEmailField.setText("");
  
    }
    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ButtonResetActionPerformed


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonSubmitStudent;
    private javax.swing.JLabel Message;
    private javax.swing.JTextField jAgeField;
    private javax.swing.JTextField jEmailField;
    private javax.swing.JTextField jFNField;
    private javax.swing.JTextField jIDField;
    private javax.swing.JTextField jLNField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPassWordField1;
    private javax.swing.JPasswordField jPassWordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jfieldusername;
    // End of variables declaration//GEN-END:variables
}
