/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import training.center.Tutor;
import training.center.MyException;
/**
 *
 * @author User
 */
public class AddTutor extends javax.swing.JPanel {

    /**
     * Creates new form AddTutor
     */
    public AddTutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFieldofficeh = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldUserName1 = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldsalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmit.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(106, 135, 157));
        btnSubmit.setText("Proceed");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(106, 135, 157));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 298, -1));

        jTextFieldofficeh.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldofficeh.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldofficeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 60, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 135, 157));
        jLabel1.setText("ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 135, 157));
        jLabel6.setText("Repeat Pass");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jTextFieldID.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldID.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 298, -1));

        jPasswordField2.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(106, 135, 157));
        add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 298, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 135, 157));
        jLabel2.setText("First name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(106, 135, 157));
        jLabel7.setText("Age");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jTextFieldFname.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldFname.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 90, -1));

        jTextFieldAge.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldAge.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 60, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(106, 135, 157));
        jLabel8.setText("Salary");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 135, 157));
        jLabel3.setText("Last name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jTextFieldLname.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldLname.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });
        add(jTextFieldLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 90, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 135, 157));
        jLabel4.setText("Email");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(106, 135, 157));
        jLabel10.setText("Office Hours");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(106, 135, 157));
        jLabel9.setText("Username");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jTextFieldUserName1.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldUserName1.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldUserName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserName1ActionPerformed(evt);
            }
        });
        add(jTextFieldUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 298, -1));

        jTextFieldemail.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldemail.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldemailActionPerformed(evt);
            }
        });
        add(jTextFieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 298, -1));

        jTextFieldsalary.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldsalary.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 60, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(106, 135, 157));
        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));
        add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 150, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beshoy sameh\\Desktop\\Project al 5ames\\GUI PHOTOS\\Admin\\add-delete teacher.jpg")); // NOI18N
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));
    }// </editor-fold>//GEN-END:initComponents
 MyException e= new MyException();
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        jTextFieldID.setText(e.CheckPositive(jTextFieldID.getText()));
        jTextFieldID.setText(e.checkFoundITutor(jTextFieldID.getText()));
        jTextFieldemail.setText(e.checkEmail(jTextFieldemail.getText()));
        jPasswordField1.setText(e.checkPassLength(jPasswordField1.getText()));
        jTextFieldUserName1.setText(e.checkFoundUserName(jTextFieldUserName1.getText()));
        jTextFieldAge.setText(e.CheckPositive(jTextFieldAge.getText()));
        jTextFieldofficeh.setText(e.CheckPositive(jTextFieldofficeh.getText()));
        jTextFieldsalary.setText(e.CheckPositive(jTextFieldsalary.getText()));
        if (!jTextFieldID.getText().equals("")  &&  !jTextFieldUserName1.getText().equals("")  && !jTextFieldFname.getText().equals("") && !jTextFieldLname.getText().equals("") && !jTextFieldemail.getText().equals("") && !jPasswordField1.getText().equals("") && !jPasswordField2.getText().equals("") && !jTextFieldAge.getText().equals("") && !jTextFieldsalary.getText().equals("") && !jTextFieldofficeh.getText().equals("")) {
            Tutor x = new Tutor();
            x.setID(Integer.parseInt(jTextFieldID.getText()));
            x.setFName(jTextFieldFname.getText());
            x.setLName(jTextFieldLname.getText());
            x.setUserName(jTextFieldemail.getText());
            if (jPasswordField1.getText().equals(jPasswordField2.getText())) {
                x.setPass(jPasswordField1.getText());
            }

            x.setAge(Integer.parseInt(jTextFieldAge.getText()));

            

            x.setHours(Integer.parseInt(jTextFieldofficeh.getText()));
            x.setSalary(Double.parseDouble(jTextFieldsalary.getText()));

            if (x.Add()) {
                Message.setText("Done");
                resetPanelData();
            } else {
               Message.setText("Failed");
            }
        } else {
           Message.setText("Please Fill All Fields");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    protected void resetPanelData() {
        jTextFieldID.setText("");
        jTextFieldFname.setText("");
        jTextFieldLname.setText("");
        jTextFieldUserName1.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jTextFieldAge.setText("");
        jTextFieldemail.setText("");
        jTextFieldofficeh.setText("");
        jTextFieldsalary.setText("");
  
    }
    private void jTextFieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldemailActionPerformed

    
    private void jTextFieldUserName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserName1ActionPerformed

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldUserName1;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldofficeh;
    private javax.swing.JTextField jTextFieldsalary;
    // End of variables declaration//GEN-END:variables
}
