/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author User
 */
public class AdminTutor extends javax.swing.JPanel {

    /**
     * Creates new form AdminTutor
     */
    GridBagLayout layout=new GridBagLayout();
    AddTutor at;
    ListTutor lt;
    UpdateTutor ut;
    public AdminTutor() {
        initComponents();
        DynamicPanel.setLayout(layout);
        at=new AddTutor();
        lt=new ListTutor();
        ut=new UpdateTutor();
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(at,c);
        DynamicPanel.add(lt,c);
        DynamicPanel.add(ut,c);
        at.setVisible(false);
        lt.setVisible(false);
        ut.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DynamicPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAddtutor = new javax.swing.JButton();
        jButtonListtutors = new javax.swing.JButton();
        jButtonUpdatetutor = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DynamicPanel.setOpaque(false);

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 480));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAddtutor.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonAddtutor.setForeground(new java.awt.Color(106, 135, 157));
        jButtonAddtutor.setText("Add Tutor");
        jButtonAddtutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddtutorActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddtutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jButtonListtutors.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonListtutors.setForeground(new java.awt.Color(106, 135, 157));
        jButtonListtutors.setText("List Tutors");
        jButtonListtutors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListtutorsActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonListtutors, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jButtonUpdatetutor.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonUpdatetutor.setForeground(new java.awt.Color(106, 135, 157));
        jButtonUpdatetutor.setText("Update/Delete Tutor");
        jButtonUpdatetutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatetutorActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonUpdatetutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 49));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddtutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddtutorActionPerformed
        // TODO add your handling code here:
        at.setVisible(true);
        lt.setVisible(false);
        ut.setVisible(false);
    }//GEN-LAST:event_jButtonAddtutorActionPerformed

    private void jButtonListtutorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListtutorsActionPerformed
        // TODO add your handling code here:
        at.setVisible(false);
        lt.setVisible(true);
        ut.setVisible(false);
    }//GEN-LAST:event_jButtonListtutorsActionPerformed

    private void jButtonUpdatetutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatetutorActionPerformed
        // TODO add your handling code here:
        at.setVisible(false);
        lt.setVisible(false);
        ut.setVisible(true);
    }//GEN-LAST:event_jButtonUpdatetutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton jButtonAddtutor;
    private javax.swing.JButton jButtonListtutors;
    private javax.swing.JButton jButtonUpdatetutor;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
