/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author User
 */
public class AdminMail extends javax.swing.JPanel {

    /**
     * Creates new form AdminTutor
     */
    GridBagLayout layout=new GridBagLayout();
     AddMail am;
     ListMails lm;
    public AdminMail() {
        initComponents();
        DynamicPanel.setLayout(layout);
        am=new AddMail();
        lm=new ListMails();
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(am,c);
        DynamicPanel.add(lm,c);
        am.setVisible(false);
        lm.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonCompose = new javax.swing.JButton();
        jButtonListmails = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCompose.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonCompose.setForeground(new java.awt.Color(106, 135, 157));
        jButtonCompose.setText("Compose E-Maill");
        jButtonCompose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComposeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCompose, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jButtonListmails.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonListmails.setForeground(new java.awt.Color(106, 135, 157));
        jButtonListmails.setText("List E-Mails");
        jButtonListmails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListmailsActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonListmails, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 557, 49));

        DynamicPanel.setOpaque(false);

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 600, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComposeActionPerformed
        // TODO add your handling code here:
        am.setVisible(true);
        lm.setVisible(false);
    }//GEN-LAST:event_jButtonComposeActionPerformed

    private void jButtonListmailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListmailsActionPerformed
        // TODO add your handling code here:
        am.setVisible(false);
        lm.setVisible(true);
    }//GEN-LAST:event_jButtonListmailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton jButtonCompose;
    private javax.swing.JButton jButtonListmails;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
