/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import training.center.Metrail;

/**
 *
 * @author Abanoub
 */
public class Materials extends javax.swing.JPanel {

    /**
     * Creates new form Materials
     */
    public Materials() {
        initComponents();
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelAvailableMaterial = new javax.swing.JLabel();
        jTextFieldSearchCourses = new javax.swing.JTextField();
        jButtonSearchCourses = new javax.swing.JButton();
        Message = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 135, 157));
        jLabel2.setText("Course");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 50, 30));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 135, 157));
        jLabel3.setText("Available");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 70, 30));
        add(jLabelAvailableMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 204, 80, 20));
        add(jTextFieldSearchCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 100, -1));

        jButtonSearchCourses.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonSearchCourses.setForeground(new java.awt.Color(106, 135, 157));
        jButtonSearchCourses.setText("Search");
        jButtonSearchCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCoursesActionPerformed(evt);
            }
        });
        add(jButtonSearchCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        Message.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        Message.setForeground(new java.awt.Color(255, 0, 0));
        add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 140, 70));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beshoy sameh\\Desktop\\Project al 5ames\\GUI PHOTOS\\Admin\\add-delete course.jpg")); // NOI18N
        Background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCoursesActionPerformed
      // TODO add your handling code here:
      if(!jTextFieldSearchCourses.equals("")){
          Metrail m = new Metrail();
          String s = ""+m.getnum();
          jLabelAvailableMaterial.setText(s );
      
      if( m.cheakMetrail (jTextFieldSearchCourses.getText())){
          Message.setText("The Material is about to run out . You have to mail the supplier");
      }
          
          }
    }//GEN-LAST:event_jButtonSearchCoursesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Message;
    private javax.swing.JButton jButtonSearchCourses;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAvailableMaterial;
    private javax.swing.JTextField jTextFieldSearchCourses;
    // End of variables declaration//GEN-END:variables
}
