/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import training.center.Course;
import training.center.MyException;
import training.center.Student;

/**
 *
 * @author Abanoub
 */
public class StudentDropcourse extends javax.swing.JPanel {

    /**
     * Creates new form Studentviewgrades
     */
    public StudentDropcourse() {
        initComponents();
        addRowsTojTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonsubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        SID = new javax.swing.JTextField();
        Message = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 350, 140));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 135, 157));
        jLabel2.setText("Regist a Course");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 160, -1));

        jButtonsubmit.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonsubmit.setForeground(new java.awt.Color(106, 135, 157));
        jButtonsubmit.setText("Submit");
        jButtonsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubmitActionPerformed(evt);
            }
        });
        add(jButtonsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 135, 157));
        jLabel4.setText("Your ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 60, 20));
        add(SID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 160, -1));
        add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 160, 20));

        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));
    }// </editor-fold>//GEN-END:initComponents
  MyException e=new MyException();
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubmitActionPerformed

        // TODO add your handling code here:
        SID.setText(e.CheckPositive(SID.getText()));
        if(!jTextField1.equals("")&&!SID.equals("")){
            Student x = new Student();
            ArrayList<Student>Students=new ArrayList<Student>();
            ArrayList<String>s=new ArrayList<String>();
            Students=x.List();
            for(int i=0;i< Students.size();i++){
                 if(Students.get(i).getID()==Integer.parseInt(SID.getText())){
                   x.setID(Students.get(i).getID());
                   x.setAge(Students.get(i).getAge());
                   x.setEmail(Students.get(i).getEmail());
                   x.setFName(Students.get(i).getFNname());
                   x.setLName(Students.get(i).getLName());
                   x.setPass(Students.get(i).getPass());
                   x.setUserName(Students.get(i).getuserName());
                   if(x.Drop(jTextField1.getText())){
                       Message.setText("Droping done");
                       jTextField1.setText("");
                   }
                   else{
                       Message.setText("Droping Undone");
                       jTextField1.setText("");
                   }
                   x.Update();
                 }

            }
        }

    }//GEN-LAST:event_jButtonsubmitActionPerformed
public void addRowsTojTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[1];
        Student co = new Student();
        ArrayList<Student> st= new ArrayList<Student>();

        st = co.List();

        for (Student C : st) {
            rowData[0] = C.listDeActive();
            model.addRow(rowData);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JTextField SID;
    private javax.swing.JButton jButtonsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
