/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import gui.Login;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import training.center.Course;
import training.center.Student;
import training.center.MyException;
/**
 *
 * @author Abanoub
 */
public class StudentAddcourse extends javax.swing.JPanel {
    Login f =new Login();
    /**
     * Creates new form StudentAddcourse
     */
    public StudentAddcourse() {
        initComponents();
       addRowsTojTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonsubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldCourse = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonsubmit.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonsubmit.setForeground(new java.awt.Color(106, 135, 157));
        jButtonsubmit.setText("Submit");
        jButtonsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubmitActionPerformed(evt);
            }
        });
        add(jButtonsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "ID", "Credit Hours", "Price in LE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 570, 120));

        jTextFieldCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCourseActionPerformed(evt);
            }
        });
        add(jTextFieldCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 160, -1));

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 135, 157));
        jLabel2.setText("Regist a course");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        Message.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        Message.setForeground(new java.awt.Color(255, 0, 0));
        add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 170, 20));

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 135, 157));
        jLabel3.setText("Your ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        SID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIDActionPerformed(evt);
            }
        });
        add(SID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, -1));

        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));
    }// </editor-fold>//GEN-END:initComponents
    MyException e=new MyException();
    private void jButtonsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubmitActionPerformed

        // TODO add your handling code here:
        SID.setText(e.CheckPositive(SID.getText()));
        if(!jTextFieldCourse.equals("")&&!SID.equals("")){
            ArrayList<Student> Studens=new ArrayList<Student>(); 
            Student y = new Student();
            ArrayList<String> s=new ArrayList<String>();
            ArrayList<String> tt=new ArrayList<String>();
             Studens=y.List();
             for(int i=0;i< Studens.size();i++){
                 if(Studens.get(i).getID()==Integer.parseInt(SID.getText())){
                    s=Studens.get(i).listDeActive();
                    tt=Studens.get(i).listActive();
                    for(int po=0;po< s.size();po++){
                        if(s.get(po).equals(jTextFieldCourse.getText())){
                           Message.setText("Course Alredy Exest");
                           jTextFieldCourse.setText("");       
                        }
                    }
                    for(int poo=0;poo< tt.size();poo++){
                        if(tt.get(poo).equals(jTextFieldCourse.getText())){
                           Message.setText("Course Alredy Exest");
                           jTextFieldCourse.setText("");       
                        }
                    }
                 }
                 else{
             ArrayList<Student> Students=new ArrayList<Student>(); 
             Student x = new Student();
             Students=x.List();
              for(int ii=0 ;ii< Students.size();ii++){
                 if(Students.get(ii).getID()==Integer.parseInt(SID.getText())){
                   x.setID(Students.get(ii).getID());
                   x.setAge(Students.get(ii).getAge());
                   x.setEmail(Students.get(ii).getEmail());
                   x.setFName(Students.get(ii).getFNname());
                   x.setLName(Students.get(ii).getLName());
                   x.setPass(Students.get(ii).getPass());
                   x.setUserName(Students.get(ii).getuserName());
                   x.Book(jTextFieldCourse.getText());
                   x.Update();
                   Message.setText("booking done book another");
                   jTextFieldCourse.setText("");
                 }
             }
                 }
             }
        }
    }//GEN-LAST:event_jButtonsubmitActionPerformed

    private void jTextFieldCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCourseActionPerformed

    private void SIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIDActionPerformed
public void addRowsTojTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[4];

        Course co = new Course();
        ArrayList<Course> Courses= new ArrayList<Course>();

        Courses = co.List();

        for (Course C : Courses) {
            rowData[0] = C.getName();
            rowData[1]= C.getID();
            rowData[2]=C.getHours();
            rowData[3] = C.getPrice();
            model.addRow(rowData);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JTextField SID;
    private javax.swing.JButton jButtonsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCourse;
    // End of variables declaration//GEN-END:variables
}
