/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.Serializable;
import javax.swing.JOptionPane;
import training.center.Grade;
import training.center.MyException;

/**
 *
 * @author Abanoub
 */
public class TutorGrades extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form TutorGrades
     */
    GridBagLayout layout=new GridBagLayout();
    ListGrades lg;
    public TutorGrades() {
        initComponents();
        DynamicPanel.setLayout(layout);
        lg=new ListGrades();
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(lg,c);
        lg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jStudentID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCourseID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jStudentGrade = new javax.swing.JTextField();
        jButtonAssign = new javax.swing.JButton();
        jButtonList = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 135, 157));
        jLabel2.setText("Student ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jStudentID.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jStudentID.setForeground(new java.awt.Color(106, 135, 157));
        add(jStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 210, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 135, 157));
        jLabel3.setText("Course ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jCourseID.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jCourseID.setForeground(new java.awt.Color(106, 135, 157));
        add(jCourseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 210, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 135, 157));
        jLabel4.setText("Student Grade");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jStudentGrade.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jStudentGrade.setForeground(new java.awt.Color(106, 135, 157));
        jStudentGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStudentGradeActionPerformed(evt);
            }
        });
        add(jStudentGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 210, -1));

        jButtonAssign.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jButtonAssign.setForeground(new java.awt.Color(106, 135, 157));
        jButtonAssign.setText("Assign");
        jButtonAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignActionPerformed(evt);
            }
        });
        add(jButtonAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jButtonList.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jButtonList.setForeground(new java.awt.Color(106, 135, 157));
        jButtonList.setText("List");
        jButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListActionPerformed(evt);
            }
        });
        add(jButtonList, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        DynamicPanel.setOpaque(false);
        add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 540, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beshoy sameh\\Desktop\\Project al 5ames\\GUI PHOTOS\\Admin\\add-delete teacher.jpg")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 530));
    }// </editor-fold>//GEN-END:initComponents
MyException e=new MyException();
    private void jButtonAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignActionPerformed
        // TODO add your handling code here:
        jCourseID.setText(e.CheckPositive(jCourseID.getText()));
        jStudentID.setText(e.CheckPositive(jStudentID.getText()));
        jStudentGrade.setText(e.CheckPositive(jStudentGrade.getText()));
        if(!jCourseID.equals("")&&!jStudentID.equals("")){
        Grade d = new Grade();
        Grade g = new Grade();
        g = d.Search(Integer.parseInt(jStudentID.getText()),Integer.parseInt(jCourseID.getText()));
        if(g.Assign(g.getSid(),g.getCid(), Float.parseFloat(jStudentGrade.getText()))){ 
        jStudentID.setText("");
        jCourseID.setText("");
        jStudentGrade.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Not valid Student didnt Take This Course Try Again :(");
        }
    }//GEN-LAST:event_jButtonAssignActionPerformed
    }
    private void jButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListActionPerformed
        // TODO add your handling code here:
        lg.setVisible(true);
    }//GEN-LAST:event_jButtonListActionPerformed

    private void jStudentGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStudentGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStudentGradeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton jButtonAssign;
    private javax.swing.JButton jButtonList;
    private javax.swing.JTextField jCourseID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jStudentGrade;
    private javax.swing.JTextField jStudentID;
    // End of variables declaration//GEN-END:variables
}
