/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import training.center.Student;
import training.center.MyException;
/**
 *
 * @author User
 */
public class UpdateStudent extends javax.swing.JPanel {

    /**
     * Creates new form UpdateStudent
     */
    public UpdateStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonUpdateStudent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ButtonDeleteStudent = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        Message = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonUpdateStudent.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        ButtonUpdateStudent.setForeground(new java.awt.Color(106, 135, 157));
        ButtonUpdateStudent.setText("Update");
        ButtonUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateStudentActionPerformed(evt);
            }
        });
        add(ButtonUpdateStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 135, 157));
        jLabel1.setText("ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        ButtonDeleteStudent.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        ButtonDeleteStudent.setForeground(new java.awt.Color(106, 135, 157));
        ButtonDeleteStudent.setText("Delete");
        ButtonDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteStudentActionPerformed(evt);
            }
        });
        add(ButtonDeleteStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jTextFieldID.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldID.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 88, 298, -1));

        jButtonSearch.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(106, 135, 157));
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 47, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 135, 157));
        jLabel2.setText("First name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 126, -1, -1));

        jTextFieldSearch.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldSearch.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 48, 424, -1));

        jTextFieldFirstName.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldFirstName.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstNameActionPerformed(evt);
            }
        });
        add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 125, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 135, 157));
        jLabel3.setText("Last name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jTextFieldLastName.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldLastName.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });
        add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 125, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 135, 157));
        jLabel4.setText("Email");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jTextFieldEmail.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 298, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(106, 135, 157));
        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(106, 135, 157));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 130, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 135, 157));
        jLabel6.setText("Repeat Pass");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jPasswordField2.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(106, 135, 157));
        add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 150, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(106, 135, 157));
        jLabel7.setText("Age");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jTextFieldAge.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jTextFieldAge.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });
        add(jTextFieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 50, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(106, 135, 157));
        jLabel8.setText("Write Student ID");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jLabel11.setFont(new java.awt.Font("Britannic Bold", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(106, 135, 157));
        jLabel11.setText("UserName");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 80, 30));

        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });
        add(jTextFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 80, -1));

        Message.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        Message.setForeground(new java.awt.Color(255, 0, 0));
        add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 150, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beshoy sameh\\Desktop\\Project al 5ames\\GUI PHOTOS\\Admin\\add-delete student.jpg")); // NOI18N
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));
    }// </editor-fold>//GEN-END:initComponents
MyException e= new MyException();
    private void ButtonUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateStudentActionPerformed
        // TODO add your handling code here:
        jTextFieldID.setText(e.CheckPositive(jTextFieldID.getText()));
        jTextFieldID.setText(e.checkFoundIdStudent(jTextFieldID.getText()));
        jTextFieldUserName.setText(e.checkFoundUserName(jTextFieldUserName.getText()));
        jTextFieldEmail.setText(e.checkEmail(jTextFieldEmail.getText()));
        jPasswordField1.setText(e.checkPassLength(jPasswordField1.getText()));
        jTextFieldAge.setText(e.CheckPositive(jTextFieldAge.getText()));
        if (!jTextFieldSearch.getText().equals("") && !jTextFieldUserName.getText().equals("") &&!jTextFieldID.getText().equals("") && !jTextFieldFirstName.getText().equals("") && !jTextFieldLastName.getText().equals("") && !jTextFieldEmail.getText().equals("") && !jPasswordField1.getText().equals("") && !jPasswordField2.getText().equals("") && !jTextFieldAge.getText().equals("")) {

            Student x = new Student();
            x.setID(Integer.parseInt(jTextFieldID.getText()));
            x.setFName(jTextFieldFirstName.getText());
            x.setLName(jTextFieldLastName.getText());
            x.setUserName(jTextFieldUserName.getText());
            x.setEmail(jTextFieldEmail.getText());
            if (jPasswordField1.getText().equals(jPasswordField2.getText())) {
                x.setPass(jPasswordField1.getText());
            }

            x.setAge(Integer.parseInt(jTextFieldAge.getText()));
           
            if (x.Update()) {
                Message.setText("Updated Successfully ... !");
                resetPanelData();
            } else {
                Message.setText("Failed to Update ... !");
            }
        } else {
            Message.setText("Missing required Fields ... !  Please, complete them before submit ...!");
        }
    }//GEN-LAST:event_ButtonUpdateStudentActionPerformed

    private void ButtonDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteStudentActionPerformed
        // TODO add your handling code here:
         if (!jTextFieldSearch.getText().equals("")) {
            Student x = new Student();
            if (x.Delete(Integer.parseInt(jTextFieldSearch.getText()))) {
                Message.setText("Deleted Successfully ... !");
                resetPanelData();
            } else {
                Message.setText("Failed to delete ... !");
            }
        } else {
            Message.setText("Missing required Fields ... !  Please, Search By ID before submit ...!");
        }
    }//GEN-LAST:event_ButtonDeleteStudentActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        jTextFieldSearch.setText(e.CheckPositive(jTextFieldSearch.getText()));
        if (!jTextFieldSearch.getText().equals("")) {
           Student x = new Student();
            Student returned = x.Search(Integer.parseInt(jTextFieldSearch.getText()));
            if (returned.getID() > 0) {
                setPanelData(returned);
            } else {
                Message.setText("Not Found ...!");
            }
        } else {
            Message.setText("Missing required Fields ... !  Please, Search By ID before submit ...!");
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    protected void resetPanelData() {
        jTextFieldSearch.setText("");
        jTextFieldUserName.setText("");
        jTextFieldID.setText("");
        jTextFieldFirstName.setText("");
        jTextFieldLastName.setText("");
        jTextFieldEmail.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jTextFieldAge.setText("");
       
    }

    protected void setPanelData(Student  x) {
      //  jTextFieldSearchCourse.setText("" + x.getID());
       // jTextFieldSearchKey.setText("");
        jTextFieldUserName.setText("" + x.getuserName() );
        jTextFieldID.setText("" + x.getID());
        jTextFieldFirstName.setText("" + x.getFNname());
        jTextFieldLastName.setText("" + x.getLName());
        jTextFieldEmail.setText("" + x.getEmail());
        jPasswordField1.setText("" + x.getPass());
        jPasswordField2.setText("" + x.getPass());
        jTextFieldAge.setText("" + x.getAge());
    }
    
    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jTextFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstNameActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDeleteStudent;
    private javax.swing.JButton ButtonUpdateStudent;
    private javax.swing.JLabel Message;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
