/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import training.center.Course;
import training.center.MyException;
//import training.center.TrainingCenter;

/**
 *
 * @author User
 */
public class UpdateCourse extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCourse
     */
    public UpdateCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabelCourseID = new javax.swing.JLabel();
        ButtonSearchCourse = new javax.swing.JButton();
        jTextFieldCourseid = new javax.swing.JTextField();
        jTextFieldSearchCourse = new javax.swing.JTextField();
        jLabelCourseName = new javax.swing.JLabel();
        jTextFieldCoursename = new javax.swing.JTextField();
        jLabelHours = new javax.swing.JLabel();
        jTextFieldCredithours = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelCourseid1 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabelCourseid2 = new javax.swing.JLabel();
        jTextFieldLecNum = new javax.swing.JTextField();
        Message = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(106, 135, 157));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        btnDelete.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(106, 135, 157));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        jLabelCourseID.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabelCourseID.setForeground(new java.awt.Color(106, 135, 157));
        jLabelCourseID.setText("course ID");
        add(jLabelCourseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        ButtonSearchCourse.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        ButtonSearchCourse.setForeground(new java.awt.Color(106, 135, 157));
        ButtonSearchCourse.setText("Search");
        ButtonSearchCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchCourseActionPerformed(evt);
            }
        });
        add(ButtonSearchCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        jTextFieldCourseid.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldCourseid.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldCourseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 200, -1));

        jTextFieldSearchCourse.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldSearchCourse.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldSearchCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchCourseActionPerformed(evt);
            }
        });
        add(jTextFieldSearchCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 247, -1));

        jLabelCourseName.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabelCourseName.setForeground(new java.awt.Color(106, 135, 157));
        jLabelCourseName.setText("Course name");
        add(jLabelCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jTextFieldCoursename.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldCoursename.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldCoursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 167, 200, 20));

        jLabelHours.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabelHours.setForeground(new java.awt.Color(106, 135, 157));
        jLabelHours.setText("Credit Hours");
        add(jLabelHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jTextFieldCredithours.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldCredithours.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldCredithours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCredithoursActionPerformed(evt);
            }
        });
        add(jTextFieldCredithours, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 135, 157));
        jLabel4.setText("Write Course ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabelCourseid1.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabelCourseid1.setForeground(new java.awt.Color(106, 135, 157));
        jLabelCourseid1.setText("Price");
        add(jLabelCourseid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jTextFieldPrice.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldPrice.setForeground(new java.awt.Color(106, 135, 157));
        add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 200, -1));

        jLabelCourseid2.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        jLabelCourseid2.setForeground(new java.awt.Color(106, 135, 157));
        jLabelCourseid2.setText("Number of Lectures");
        add(jLabelCourseid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jTextFieldLecNum.setFont(new java.awt.Font("Britannic Bold", 0, 10)); // NOI18N
        jTextFieldLecNum.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldLecNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLecNumActionPerformed(evt);
            }
        });
        add(jTextFieldLecNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 200, -1));

        Message.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beshoy sameh\\Desktop\\Project al 5ames\\GUI PHOTOS\\Admin\\add-delete course.jpg")); // NOI18N
        Message.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 150, 30));
    }// </editor-fold>//GEN-END:initComponents
MyException e= new MyException();
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        jTextFieldCourseid.setText(e.CheckPositive(jTextFieldCourseid.getText()));
        jTextFieldCourseid.setText(e.checkFoundIdCours(jTextFieldCourseid.getText()));
        jTextFieldCoursename.setText(e.checkFoundNameCours(jTextFieldCoursename.getText()));
        jTextFieldPrice.setText(e.CheckPositive(jTextFieldPrice.getText()));
        jTextFieldLecNum.setText(e.CheckPositive(jTextFieldLecNum.getText()));
        jTextFieldCredithours.setText(e.CheckPositive(jTextFieldCredithours.getText()));
        if (!jTextFieldSearchCourse.getText().equals("") && !jTextFieldCourseid.getText().equals("") && !jTextFieldCoursename.getText().equals("")  && !jTextFieldCredithours.getText().equals("") && !jTextFieldPrice.getText().equals("") && !jTextFieldLecNum.getText().equals("")  ) {

            Course x = new Course();
            x.setID(Integer.parseInt(jTextFieldCourseid.getText()));
            x.setName(jTextFieldCoursename.getText());
            x.setHours(Integer.parseInt(jTextFieldCredithours.getText()));
            x.setPrice(Double.parseDouble(jTextFieldPrice.getText()));
            x.setLecNum(Integer.parseInt(jTextFieldLecNum.getText()));
            if (x.Update()) {
                Message.setText("Updated Successfully ... !");
                resetPanelData();
            } else {
                Message.setText("Failed to Update ... !");
            }
        } else {
            Message.setText("Missing required Fields ... !  Please, complete them before submit ...!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldSearchCourse.getText().equals("")) {
            Course x = new Course();
            if (x.Delete(Integer.parseInt(jTextFieldSearchCourse.getText())) ){
                Message.setText("Deleted Successfully ... !");
                resetPanelData();
            } else {
                Message.setText("Failed to delete ... !");
            }
        } else {
            Message.setText("Missing required Fields ... !  Please, Search By ID before submit ...!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void ButtonSearchCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchCourseActionPerformed
        // TODO add your handling code here:
        jTextFieldSearchCourse.setText(e.CheckPositive(jTextFieldSearchCourse.getText()));
        if (!jTextFieldSearchCourse.getText().equals("")) {
            Course x = new Course();
            Course returned = x.Search(Integer.parseInt(jTextFieldSearchCourse.getText()));
            if (returned.getID() > 0) {
                setPanelData(returned);
            } else {
                Message.setText("Not Found ...!");
            }
        } else {
            Message.setText("Missing required Fields ... !  Please, Search By ID before submit ...!");
        }
    }//GEN-LAST:event_ButtonSearchCourseActionPerformed

    protected void resetPanelData() {
        jTextFieldSearchCourse.setText("");
        jTextFieldCourseid.setText("");
        jTextFieldCoursename.setText("");
        jTextFieldCredithours.setText("");
        jTextFieldPrice.setText("");
        jTextFieldLecNum.setText("");
     
    }

    protected void setPanelData(Course x) {
      //  jTextFieldSearchCourse.setText("" + x.getID());
        jTextFieldCourseid.setText("" + x.getID());
        jTextFieldCoursename.setText("" + x.getName());
        jTextFieldCredithours.setText("" + x.getHours());
        jTextFieldLecNum.setText("" + x.getLecNum());
        jTextFieldPrice.setText("" + x.getPrice());
        
    }

    private void jTextFieldCredithoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCredithoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCredithoursActionPerformed

    private void jTextFieldSearchCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchCourseActionPerformed

    private void jTextFieldLecNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLecNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLecNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSearchCourse;
    private javax.swing.JLabel Message;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCourseID;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JLabel jLabelCourseid1;
    private javax.swing.JLabel jLabelCourseid2;
    private javax.swing.JLabel jLabelHours;
    private javax.swing.JTextField jTextFieldCourseid;
    private javax.swing.JTextField jTextFieldCoursename;
    private javax.swing.JTextField jTextFieldCredithours;
    private javax.swing.JTextField jTextFieldLecNum;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldSearchCourse;
    // End of variables declaration//GEN-END:variables
}
