/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import training.center.User;
import training.center.Admin;
import training.center.Student;
import training.center.Tutor;
import training.center.MyException;
import Panels.*;

/**
 *
 * @author Abanoub
 */
public class Login extends javax.swing.JFrame {
    public String s="";
    public String  z="";
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    public void Loogin (String ss,String zz){
       if(!ss.equals("")&&!zz.equals(""))
        {
            User x;
            x = new Admin();
            if ((x.login(ss,zz))) {
            this.setVisible(false);
            
            AdminMain a=new AdminMain();
                   a.ss=ss;
                   a.tt=zz;
                    a.setVisible(true);
                    StudentAddcourse c=new StudentAddcourse();
                   
                    
        } else {
            x = new Student();
            if (x.login(ss,zz)) {
                this.setVisible(false);
                StudentMain a=new StudentMain();
                   a.ss=ss;
                   a.tt=zz;
                    a.setVisible(true);
                  StudentAddcourse c=new StudentAddcourse();
                   
            }
        else{
                x = new Tutor();
                if ((x.login(ss,zz))) {
                this.setVisible(false);
                TutorMain a=new TutorMain();
                   a.ss=ss;
                   a.tt=zz;
                    a.setVisible(true);
                    StudentAddcourse c=new StudentAddcourse();
            }
        }
      }
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEKLOGIN = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        jTextFieldUsernamr = new javax.swing.JTextField();
        BKusername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        BKpassword = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEKLOGIN.setFont(new java.awt.Font("Bell MT", 0, 25)); // NOI18N
        jEKLOGIN.setForeground(new java.awt.Color(106, 135, 157));
        jEKLOGIN.setText("EK | LOGIN");
        getContentPane().add(jEKLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 98, 140, 40));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 135, 157));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 198, 100, -1));

        username1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 198, 100, 30));

        jTextFieldUsernamr.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        jTextFieldUsernamr.setForeground(new java.awt.Color(106, 135, 157));
        jTextFieldUsernamr.setBorder(null);
        jTextFieldUsernamr.setOpaque(false);
        jTextFieldUsernamr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernamrActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsernamr, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 228, 230, 30));

        BKusername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(BKusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 228, 230, 30));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 135, 157));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 328, 100, -1));

        Password.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 328, 100, 30));

        jPasswordField.setForeground(new java.awt.Color(106, 135, 157));
        jPasswordField.setBorder(null);
        jPasswordField.setOpaque(false);
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 358, 230, 30));

        BKpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(BKpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 358, 230, 30));

        jButton1.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(106, 135, 157));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 478, 73, -1));

        jButton2.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(106, 135, 157));
        jButton2.setText("Reset");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 478, 73, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beshoy sameh\\Desktop\\Project al 5ames\\GUI PHOTOS\\Admin\\Login.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
MyException e=new MyException();
    private void jTextFieldUsernamrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernamrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernamrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          s=jTextFieldUsernamr.getText();
          StudentAddcourse c=new StudentAddcourse();
          z=jPasswordField.getText();
        jPasswordField.setText(e.checkPassLength(jPasswordField.getText()));
        User x;
        x = new Admin();
        if ((x.login(jTextFieldUsernamr.getText(), jPasswordField.getText()))) {
            this.setVisible(false);
             AdminMain a=new AdminMain();
                   a.ss=jTextFieldUsernamr.getText();
                   a.tt=jPasswordField.getText();
                    a.setVisible(true);
        } else {
            x = new Student();
            if ((x.login(jTextFieldUsernamr.getText(), jPasswordField.getText()))) {
                this.setVisible(false);
                 StudentMain a=new StudentMain();
                   a.ss=jTextFieldUsernamr.getText();
                   a.tt=jPasswordField.getText();
                    a.setVisible(true);
            }
        else{
                x = new Tutor();
                if ((x.login(jTextFieldUsernamr.getText(), jPasswordField.getText()))) {
                this.setVisible(false);
                 TutorMain a=new TutorMain();
                   a.ss=jTextFieldUsernamr.getText();
                   a.tt=jPasswordField.getText();
                    a.setVisible(true);
            }
        }
      }
    }//GEN-LAST:event_jButton1ActionPerformed
public final String bv=s;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BKpassword;
    private javax.swing.JLabel BKusername;
    private javax.swing.JLabel Password;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jEKLOGIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsernamr;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables
}
