/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Panels.StudentAddcourse;
import Panels.StudentAttendance;
import Panels.StudentDropcourse;
import Panels.StudentFeedbacks;
import Panels.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class StudentMain extends javax.swing.JFrame {

    /**
     * Creates new form StudentMain
     */
    public   String ss;
    public   String tt;
    Login xx=new Login();
    GridBagLayout layout=new GridBagLayout();
    StudentAddcourse sc;
    StudentAttendance sa;
    StudentDropcourse sd;
    StudentFeedbacks sf;
    StudentGrade sg;
    MyCourses cor;
    public StudentMain() {
        initComponents();
        DynamicPanel.setLayout(layout);
    sc=new StudentAddcourse();
    sa=new StudentAttendance();
    sd=new StudentDropcourse();
    sf=new StudentFeedbacks();
    sg=new StudentGrade();
    cor=new MyCourses();
    GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(sc,c);
        DynamicPanel.add(sa,c);
        DynamicPanel.add(sd,c);
        DynamicPanel.add(sf,c);
        DynamicPanel.add(sg,c);
        sc.setVisible(false);
        sa.setVisible(false);
        sd.setVisible(false);
        sf.setVisible(false);
        sg.setVisible(false);
        cor.setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSAddcourse = new javax.swing.JButton();
        jButtonSCourses = new javax.swing.JButton();
        jButtonSAddfeedback = new javax.swing.JButton();
        Coursespanel = new javax.swing.JPanel();
        jButtonSViewattendance = new javax.swing.JButton();
        jButtonSDropcourse = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        Refresh = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSAddcourse.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonSAddcourse.setForeground(new java.awt.Color(106, 135, 157));
        jButtonSAddcourse.setText("Add new course");
        jButtonSAddcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAddcourseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSAddcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 120, -1));

        jButtonSCourses.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonSCourses.setForeground(new java.awt.Color(106, 135, 157));
        jButtonSCourses.setText("My Courses");
        jButtonSCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSCoursesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 120, -1));

        jButtonSAddfeedback.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonSAddfeedback.setForeground(new java.awt.Color(106, 135, 157));
        jButtonSAddfeedback.setText("Add Feedbacks");
        jButtonSAddfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAddfeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSAddfeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 121, -1));

        Coursespanel.setOpaque(false);

        jButtonSViewattendance.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonSViewattendance.setForeground(new java.awt.Color(106, 135, 157));
        jButtonSViewattendance.setText("View Attendance");
        jButtonSViewattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSViewattendanceActionPerformed(evt);
            }
        });

        jButtonSDropcourse.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButtonSDropcourse.setForeground(new java.awt.Color(106, 135, 157));
        jButtonSDropcourse.setText("Drop Course");
        jButtonSDropcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSDropcourseActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Britannic Bold", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(106, 135, 157));
        jButton1.setText("View Grades");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CoursespanelLayout = new javax.swing.GroupLayout(Coursespanel);
        Coursespanel.setLayout(CoursespanelLayout);
        CoursespanelLayout.setHorizontalGroup(
            CoursespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoursespanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonSViewattendance, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButtonSDropcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoursespanelLayout.setVerticalGroup(
            CoursespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoursespanelLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(CoursespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSDropcourse)
                    .addComponent(jButtonSViewattendance)
                    .addComponent(jButton1)))
        );

        getContentPane().add(Coursespanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        DynamicPanel.setOpaque(false);

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 490));

        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 610));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jMenu1.setBackground(new java.awt.Color(204, 204, 204));
        jMenu1.setText("File");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Logout");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        Refresh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jMenu1.add(Refresh);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(204, 204, 204));
        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSAddcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAddcourseActionPerformed
        // TODO add your handling code here:
        sc.setVisible(true);
        cor.setVisible(false);
        sa.setVisible(false);
        sd.setVisible(false);
        sf.setVisible(false);
        sg.setVisible(false);
    }//GEN-LAST:event_jButtonSAddcourseActionPerformed

    private void jButtonSCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSCoursesActionPerformed
        // TODO add your handling code here:
        sc.setVisible(false);
        sa.setVisible(false);
        sd.setVisible(false);
        sf.setVisible(false);
        sg.setVisible(false);
        cor.setVisible(true);
    }//GEN-LAST:event_jButtonSCoursesActionPerformed

    private void jButtonSAddfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAddfeedbackActionPerformed
        // TODO add your handling code here:
        sc.setVisible(false);
        cor.setVisible(false);
        sa.setVisible(false);
        sd.setVisible(false);
        sf.setVisible(true);
        sg.setVisible(false);
    }//GEN-LAST:event_jButtonSAddfeedbackActionPerformed

    private void jButtonSDropcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSDropcourseActionPerformed
        // TODO add your handling code here:
        sc.setVisible(false);
        sa.setVisible(false);
        sd.setVisible(true);
        cor.setVisible(false);
        sf.setVisible(false);
        sg.setVisible(false);
    }//GEN-LAST:event_jButtonSDropcourseActionPerformed

    private void jButtonSViewattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSViewattendanceActionPerformed
        // TODO add your handling code here:
        sc.setVisible(false);
        sa.setVisible(true);
        sd.setVisible(false);
        sf.setVisible(false);
        cor.setVisible(false);
        sg.setVisible(false);
    }//GEN-LAST:event_jButtonSViewattendanceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sc.setVisible(false);
        sa.setVisible(false);
        sd.setVisible(false);
        sf.setVisible(false);
        cor.setVisible(false);
        sg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
int c = JOptionPane.showConfirmDialog(null, "Are you Sure, System will Exit");
        if (c == JOptionPane.OK_OPTION) {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        xx.Loogin(ss, tt);
        this.setVisible(false);
    }//GEN-LAST:event_RefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Coursespanel;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JMenuItem Refresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSAddcourse;
    private javax.swing.JButton jButtonSAddfeedback;
    private javax.swing.JButton jButtonSCourses;
    private javax.swing.JButton jButtonSDropcourse;
    private javax.swing.JButton jButtonSViewattendance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
